#!/bin/bash

# Audio sinks
HEADSET=$(pactl list sinks | grep "alsa_output.usb-C-Media_Electronics_Inc._Redragon_Gaming_Headset-00" | awk {'print $2'} | grep alsa)
SPEAKERS=$(pactl list sinks | grep alsa_output.pci | awk {'print $2'} | grep alsa)


# Get current audio sink
CURRENTDEV=$(pactl list short sinks | grep RUNNING | awk {'print $2'})

# Determine our next audio sink
if [[ "$CURRENTDEV" == "$HEADSET" ]]; then
    	NEXTDEV=$SPEAKERS
	notify-send 'Audio device changed to speakers' -u normal -i audio-speakers-symbolic
else
	NEXTDEV=$HEADSET
	notify-send 'Audio device changed to headset' -u normal -i audio-headphones-symbolic
fi

# Set our default device
pactl set-default-sink $NEXTDEV


# Move current streams (dont check for null, if null you wont see heads up display of audio change)
INPUTS=($(pacmd list-sink-inputs | grep index | awk '{print $2}'))
for i in ${INPUTS[*]}; do pacmd move-sink-input $i $NEXTDEV &> /dev/null; done
