#!/bin/sh

DEVICE="alsa_input.usb-C-Media_Electronics_Inc._Redragon_Gaming_Headset-00.9.mono-fallback"
MUTED=$(pactl get-source-mute $DEVICE)
VOLUME=$(pactl get-source-volume $DEVICE | awk {'print $5'})

if [[ $MUTED == "Mute: yes" ]]; then
  echo -e "%{F#6a6b6b}   $VOLUME%{F-}" # Muted
else
  echo -e "   $VOLUME" # Unmuted
fi
