#!/bin/sh

MUTED=$(pamixer --get-mute)

if [[ $MUTED == "false" ]]; then
	pamixer --mute
	notify-send "Audio muted" -i audio-volume-muted-symbolic
fi

if [[ $MUTED == "true" ]]; then
    pamixer --unmute
    notify-send "Audio unmuted" -i audio-speakers-symbolic
fi
