#!/bin/bash

sudo -v
clear

echo -e "Atualizando pacotes RPM\n"
sudo dnf update -y && sudo dnf upgrade -y
sleep 1
clear
wait

echo -e "Atualizando Flatpaks\n"
flatpak update -y
sleep 1
clear
wait

echo -e "Atualizando Snaps\n"
snap refresh
clear
wait

echo -e "Tudo foi atualizado meu chapa"
sleep 1
wait
clear


